Detect implicit TBB dependence of parallel STL
ROCm-Developer-Tools/HIP-CPU pull request #13
Opened 2021-01-12 14:17 UTC by MathiasMagnus

This PR addresses #11.

It includes the lightest of STL headers in C++17 mode which immediately pulls in `bits/c++config.h` which in turn includes `pstl/pstl_config.h` which exposes the half-baked machinery of PSTL back-end detection and simply defaults to TBB.

![image](https://user-images.githubusercontent.com/9763499/104324703-10723c80-54e8-11eb-8f6b-e91fa61b50b4.png)

CMake script looks for the macro `__PSTL_PAR_BACKEND_TBB ` and if present searches for TBB and links to it.

_(Note: does not support TBB versions prior to 2017 [as per the docs](https://github.com/oneapi-src/oneTBB/tree/2018_U6/cmake#binary-package-integration), but that shouldn't matter, as minimum requirements for PSTL is 2018.)_

2021-01-12 16:40 UTC, MathiasMagnus commented
@AlexVlx How can the macOS tests fail due to these changes? Tests seem to be timing out.

2021-01-12 16:44 UTC, AlexVlx requested changes
LGTM modulo the question and my suspicion that it might be necessary to tweak this a bit for macOS, where there's no system TBB and its CMake modules would not be part of the default CMAKE_PREFIX_PATH.

2021-01-12 16:44 UTC, AlexVlx commented on CMakeLists.txt
> +        target_link_libraries(
Are we missing a `find_package(TBB REQUIRED)` here perchance?

2021-01-12 16:44 UTC, AlexVlx commented
> @AlexVlx How can the macOS tests fail due to these changes? Tests seem to be timing out.

That's an unrelated (known) failure, please ignore.

2021-01-25 13:45 UTC, MathiasMagnus commented
I'll revisit the issue this week. (At least that's the plan.)

2021-01-28 14:02 UTC, MathiasMagnus commented on CMakeLists.txt
> +        target_link_libraries(
Added.

2021-01-28 15:41 UTC, MathiasMagnus commented
I added the missing TBB detection and it builds on all platforms and just "regularly" timeouts on macOS.

2021-01-28 15:41 UTC, merged

2021-01-28 15:41 UTC, AlexVlx commented
Merged, thank you.