Cmake fixes
ROCm-Developer-Tools/HIP-CPU pull request #16
Opened 2021-02-01 21:55 UTC by MathiasMagnus

This PR fixes a typo in build interface include dirs and deduplicates some login in test and benchmark definitions.

2021-02-03 11:19 UTC, AlexVlx commented
@MathiasMagnus  thank you for submitting this, but I believe that streams might've gotten crossed? For example, we don't want to disable Linux & Windows CI testing - perhaps this needs a bit of a cleanup / separation?

2021-02-03 12:49 UTC, MathiasMagnus commented
Yes, apologies, this is still a WIP. CI is only enabled for the master branch and not for working branches. Could we borrow the [Draft PR feature](https://github.blog/2019-02-14-introducing-draft-pull-requests/) of GitHub? I don't think it's enabled for this repo. It works very well on Vcpkg and is useful for messaging that something is half baked.

As a contributor, when I'm opening a PR, there are two buttons, one is regular PR and the other is Draft PR. It's similar to starting the PR name with "WIP:" on GitLab. The UI changes and clearly states it's not meant for merging, but allows feedback from upstream whether they like the design or not.

2021-02-03 12:54 UTC, MathiasMagnus commented
I Linux and Windows and many things to speed up CI runtimes while all tests are supposed to fail building/executing the same way. I intended to turn them back on once the work is done.

2021-02-05 21:09 UTC, AlexVlx commented
> Yes, apologies, this is still a WIP. CI is only enabled for the master branch and not for working branches. Could we borrow the [Draft PR feature](https://github.blog/2019-02-14-introducing-draft-pull-requests/) of GitHub? I don't think it's enabled for this repo. It works very well on Vcpkg and is useful for messaging that something is half baked.
> 
> As a contributor, when I'm opening a PR, there are two buttons, one is regular PR and the other is Draft PR. It's similar to starting the PR name with "WIP:" on GitLab. The UI changes and clearly states it's not meant for merging, but allows feedback from upstream whether they like the design or not.

I'm afraid that we're not going to have Draft PRs for the time being, since as far as I can gather they're not available for the sort of account that's underpinning this repository. Perhaps at some point in the future, it is a very useful feature.

2021-03-04 11:05 UTC, MathiasMagnus commented
@AlexVlx Requesting review. I have removed some code duplication in test and example code definitions, also finished moving away from manual control of include and link library additions (especially those added through global state) and consolidated picking up dependencies to imported targets. Build flags are also managed through imported target with compiler-specific branches handles through generator expressions instead of script logic.

The only (intended) functional difference is adding `/W4` to the MSVC build flags, as other compilers tend to be used in a similar fashion. Let me know if that's too much. There are a few interesting messages on the console:
- `warning C5105: macro expansion producing 'defined' has undefined behavior`
- `warning C4068: unknown pragma 'unroll'`

### Segue

FWIW I would completely move away from adding flags via build scripts which aren't essential for the compilation to succeed. I didn't know what was missing from my (professional) life until I came across [this tweet](https://twitter.com/JSAMcFarlane/status/1252330666722758658?s=20). Build scripts (ideally, at least in my ideal world) would define build requirements only (required lang standards, ABI altering reqs, etc.), not build preferences (diagnostic, optimization levels). It may be something worth considering.

One hot topic internally was adding `-Werror` and `/WX` to the scripts by default, because we want to compile warning-free at given warning levels. It constantly tripped people over, who were using newer compilers than the ones others CI was using and it made everyone be constantly adding workarounds to warnings others introduced which CI did not alert us to, because CI images usually don't use bleeding edge compilers.

Long story short (IMHO):
- if libs should compile warning free, add `-Werror`, `/WX` and the target warning levels/flags to CI scripts _only_ and don't trip over casual devs cloning your repo.
- if devs want to see `info C5002: loop not vectorized due to reason '500'` messages, configure CI/devenv accordingly. (I guess this is produced by `/Qvec-report:2`.
- is `/arch:AVX2` a build requirement? Should a project wait for the first Windows user targeting ARM64 to face conflicting arch definitions or should these be in CI only where the execution environment is known?

2021-04-27 12:37 UTC, AlexVlx requested changes

2021-04-27 12:37 UTC, AlexVlx commented on examples/CMakeLists.txt
> +)
Please re-format this to match the rest of the codebase i.e. no trailing parentheses, clear newline after the opening parenthese and no extra vertical spacing (reckon the full line might fit within the 80 character limit but, if not, the argument to `target_link_libraries` will fit once you've put it on its own line)

2021-04-27 12:37 UTC, AlexVlx commented on examples/CMakeLists.txt
> +target_compile_options(examples_common
I don't think we really need these, they're historical artifacts I didn't clean up before going public, these should be under user control and not enforced.

2021-04-27 12:37 UTC, AlexVlx commented on examples/CMakeLists.txt
> +target_compile_definitions(examples_common
We do need this, but please match style.

2021-04-27 12:37 UTC, AlexVlx commented on examples/bit_extract/CMakeLists.txt
> +target_link_libraries(${name}
Please match style.

2021-04-27 12:37 UTC, AlexVlx commented on examples/hip_bus_bandwidth/CMakeLists.txt
> +target_link_libraries(${name}
Please match style.

2021-04-27 12:37 UTC, AlexVlx commented on examples/hip_dispatch_enqueue_rate_mt/CMakeLists.txt
> +target_link_libraries(${name}
Please match style.

2021-04-27 12:37 UTC, AlexVlx commented on examples/hip_dispatch_latency/CMakeLists.txt
> +target_link_libraries(${name}
Please match style.

2021-04-27 12:37 UTC, AlexVlx commented on examples/hip_event/CMakeLists.txt
> +target_link_libraries(${name}
Please match style.

2021-04-27 12:37 UTC, AlexVlx commented on examples/hip_info/CMakeLists.txt
> +target_link_libraries(${name}
Please match style.

2021-04-27 12:37 UTC, AlexVlx commented on examples/matrix_transpose/CMakeLists.txt
> +target_link_libraries(${name}
Please match style.

2021-04-27 12:37 UTC, AlexVlx commented on examples/occupancy/CMakeLists.txt
> +target_link_libraries(${name}
Please match style.

2021-04-27 12:37 UTC, AlexVlx commented on examples/pragma_unroll/CMakeLists.txt
> +target_link_libraries(${name}
Please match style.

2021-04-27 12:37 UTC, AlexVlx commented on examples/shared_memory/CMakeLists.txt
> +target_link_libraries(${name}
Please match style.

2021-04-27 12:37 UTC, AlexVlx commented on examples/square/CMakeLists.txt
> +target_link_libraries(${name}
Please match style.

2021-04-27 12:37 UTC, AlexVlx commented on examples/streams/CMakeLists.txt
> +target_link_libraries(${name}
Please match style.

2021-04-27 12:37 UTC, AlexVlx commented on examples/vadd_hip/CMakeLists.txt
> +target_link_libraries(${name}
Please match style.

2021-04-27 12:37 UTC, AlexVlx commented on tests/CMakeLists.txt
> +target_link_libraries(legacy_tests
Please match style.

2021-04-27 12:37 UTC, AlexVlx commented on tests/CMakeLists.txt
> +target_link_libraries(performance_tests
Please match style.

2021-04-27 12:37 UTC, AlexVlx commented on tests/CMakeLists.txt
> +        # CMake 3.19 required for list in $<CONFIG:cfg1,cfg2> for shorthand
I think even for something that is as daring as HIP-CPU, taking a dependency on CMake 3.19 is a bit too much since various upstream repositories are not quite there yet and asking the user to deal with it would add needless friction, so this should be refactored, even though it's sweet sugar.

2021-04-27 12:37 UTC, AlexVlx commented on src/CMakeLists.txt
> +target_compile_options(src_common
Probably don't need this.

2021-04-27 12:37 UTC, AlexVlx commented on src/CMakeLists.txt
> +target_compile_definitions(src_common
We do need this, but please match style.

2021-04-27 12:37 UTC, AlexVlx commented on src/hip/CMakeLists.txt
> +add_executable(public_interface_tests
Please match style.

2021-04-27 12:37 UTC, AlexVlx commented on src/hip/CMakeLists.txt
> +add_test(
Please match style.

2021-04-27 12:37 UTC, AlexVlx commented on tests/CMakeLists.txt
> +target_link_libraries(tests_common
Please match style.

2021-04-27 12:37 UTC, AlexVlx commented on tests/CMakeLists.txt
> +target_compile_options(tests_common
Probably don't need this.

2021-04-27 12:37 UTC, AlexVlx commented on tests/CMakeLists.txt
> +target_compile_definitions(tests_common
We do need this but please match style.

2021-04-27 12:38 UTC, AlexVlx commented
@MathiasMagnus thank you again for submitting this and apologies for the long delay in reviewing it. In general LGTM, but there are a few things that would increase tidiness, so please go over the comments.

2021-04-27 16:02 UTC, MathiasMagnus commented
Thanks, will fix the issues once I get there. rocPRIM will soon land experimental HIP-CPU support, currently with many algos failing, just getting everything to compile using MSVC/GCC/Clang. (Some simple tests do pass). Perhaps at one point HIP-CPU can adopt rocPRIM into it's CI for some massive testing.

2021-04-27 18:55 UTC, AlexVlx commented
> Thanks, will fix the issues once I get there. rocPRIM will soon land experimental HIP-CPU support, currently with many algos failing, just getting everything to compile using MSVC/GCC/Clang. (Some simple tests do pass). Perhaps at one point HIP-CPU can adopt rocPRIM into it's CI for some massive testing.

Thank you. Regarding rocPRIM, it'll definitely find its way into the CI infrastructure, the more the merrier:)

2021-06-10 13:04 UTC, MathiasMagnus commented
> I think even for something that is as daring as HIP-CPU, taking a dependency on CMake 3.19 is a bit too much since various upstream repositories are not quite there yet and asking the user to deal with it would add needless friction, so this should be refactored, even though it's sweet sugar. 

Indeed, that's just a note that once someone bumps minimum requirements, those lines can be merged.

2021-06-10 13:18 UTC, MathiasMagnus commented on examples/CMakeLists.txt
> +)
Hope I got the styling right.

2021-06-10 13:19 UTC, MathiasMagnus commented on examples/CMakeLists.txt
> +target_compile_options(examples_common
Good.

2021-06-10 13:19 UTC, MathiasMagnus commented on examples/CMakeLists.txt
> +target_compile_definitions(examples_common
Done.

2021-06-10 13:19 UTC, MathiasMagnus commented on examples/bit_extract/CMakeLists.txt
> +target_link_libraries(${name}
Done.

2021-06-10 13:19 UTC, MathiasMagnus commented on examples/hip_bus_bandwidth/CMakeLists.txt
> +target_link_libraries(${name}
Done.

2021-06-10 13:19 UTC, MathiasMagnus commented on src/hip/CMakeLists.txt
> +add_executable(public_interface_tests
Done.

2021-06-10 13:19 UTC, MathiasMagnus commented on src/CMakeLists.txt
> +target_compile_definitions(src_common
Done.

2021-06-10 13:19 UTC, MathiasMagnus commented on src/hip/CMakeLists.txt
> +add_test(
Done.

2021-06-10 13:19 UTC, MathiasMagnus commented on tests/CMakeLists.txt
> +target_link_libraries(tests_common
Done.

2021-06-10 13:19 UTC, MathiasMagnus commented on tests/CMakeLists.txt
> +target_compile_definitions(tests_common
Done.

2021-06-10 13:20 UTC, MathiasMagnus commented on examples/hip_dispatch_latency/CMakeLists.txt
> +target_link_libraries(${name}
Done.

2021-06-10 13:20 UTC, MathiasMagnus commented on examples/hip_info/CMakeLists.txt
> +target_link_libraries(${name}
Done.

2021-06-10 13:20 UTC, MathiasMagnus commented on examples/matrix_transpose/CMakeLists.txt
> +target_link_libraries(${name}
Done.

2021-06-10 13:20 UTC, MathiasMagnus commented on examples/pragma_unroll/CMakeLists.txt
> +target_link_libraries(${name}
Done.

2021-06-10 13:20 UTC, MathiasMagnus commented on examples/shared_memory/CMakeLists.txt
> +target_link_libraries(${name}
Done.

2021-06-10 13:20 UTC, MathiasMagnus commented on examples/square/CMakeLists.txt
> +target_link_libraries(${name}
Done.

2021-06-10 13:20 UTC, MathiasMagnus commented on examples/streams/CMakeLists.txt
> +target_link_libraries(${name}
Done.

2021-06-10 13:20 UTC, MathiasMagnus commented on examples/vadd_hip/CMakeLists.txt
> +target_link_libraries(${name}
Done.

2021-06-10 13:22 UTC, MathiasMagnus commented on tests/CMakeLists.txt
> +target_link_libraries(legacy_tests
Done.

2021-06-10 13:22 UTC, MathiasMagnus commented on tests/CMakeLists.txt
> +target_link_libraries(performance_tests
Done.

2021-06-10 13:23 UTC, MathiasMagnus commented on tests/CMakeLists.txt
> +        # CMake 3.19 required for list in $<CONFIG:cfg1,cfg2> for shorthand
Indeed, that's just a note that once someone bumps minimum requirements, those lines can be merged.

2021-06-10 13:23 UTC, MathiasMagnus commented on src/CMakeLists.txt
> +target_compile_options(src_common
Done.

2021-06-10 13:23 UTC, MathiasMagnus commented on tests/CMakeLists.txt
> +target_compile_options(tests_common
Indeed, that's just a note that once someone bumps minimum requirements, those lines can be merged.

2021-06-10 13:24 UTC, MathiasMagnus reviewed
I think I addressed all issues, plus rebased my work on to tip of master.

2021-06-11 08:15 UTC, merged

2021-06-11 08:15 UTC, AlexVlx commented
@MathiasMagnus thank you very much for this and for making the changes (I did a wee bit of tinkering out of pure pedantry, I hope you don't mind), but overall LGTM!

2021-06-11 18:58 UTC, MathiasMagnus commented
No problem. I couldn't quite figure out the style you were looking for based on the textual desc and the root CMakelists.txt. Maybe one day we'll have semantic aware "Clang-tidy" for CMake scripts.